first commit
fu10ta/quelcode-db pull request #2
Opened 2020-09-01 07:29 UTC by fu10ta

DB課題②物理設計とDDL文の作成をいたしました。

2020-09-01 07:29 UTC, fu10ta commented
DB課題②物理設計とDDL文の作成をいたしました。

2020-09-01 13:29 UTC, himaru-jp requested changes
同じ内容の指摘はしていませんので、合わせて修正するようお願いします。
DDLと仕様書に相違がないように修正をお願いします。

2020-09-01 13:29 UTC, himaru-jp commented on db/db-challenge2/init.sql
> +      `modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
created_atに倣うならmodified_atとした方が分かりやすいと思います。
またupdated_user_idが存在するのであれば、updated_atと統一すると関連していることが分かりやすいです。

2020-09-01 13:29 UTC, himaru-jp commented on db/db-challenge2/init.sql
> +      `created_at` datetime NOT NULL,
modifiedと同様にデフォルト値をセットしましょう。

2020-09-01 13:29 UTC, himaru-jp commented on db/db-challenge2/init.sql
> +) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1;
要件にある通り、トランザクションが利用できるデータベースエンジンの指定を追加しましょう。

2020-09-01 13:29 UTC, himaru-jp commented on db/db-challenge2/init.sql
> +    `is_conpleted` tinyint(1) NOT NULL DEFAULT 0,
completedのスペルミスのようです。

2020-09-01 13:29 UTC, himaru-jp commented on db/db-challenge2/init.sql
> +    `admin_id` int(11) NOT NULL,
admin_idではどのような役割のユーザなのか分かりづいため再考してみてください。

2020-09-01 13:29 UTC, himaru-jp commented on db/db-challenge2/init.sql
> +    `limited_at` datetime,
過去形_atですと、それを行った日付が入っていると認識してしまいます。
再考をお願いします。

2020-09-01 13:29 UTC, himaru-jp commented on db/db-challenge2/init.sql
> +CREATE TABLE `members`(
membersではユーザ一覧が保存されているように誤認します。
どのようなデータかもう少し具体的な名称にするか、
中間テーブルとしての慣習に倣い、二つのテーブル名をつけてrooms_users または rooms_usersテーブルで良いと思います。

2020-09-02 04:13 UTC, fu10ta commented
レビュー修正をいたしました。

2020-09-03 00:23 UTC, fu10ta commented
レビュー修正とDDL実行順を変更いたしました。

2020-09-03 02:06 UTC, Yuzunoha commented
レビュー終わったら✓
- [ ] DBエンジン
- [ ] users
- [ ] users_rooms
- [ ] rooms
- [ ] posts
- [ ] tasks

2020-09-03 02:16 UTC, Yuzunoha commented
user_やpost_ といった、カラム名に自分のテーブルの接頭辞(プレフィックス)を付けるのを止めましょう。
emailはuser_emailじゃなくてよいのか、接頭辞あるなしの違いは？となるので。
users.user_idよりusers.idの方がすっきりします。

外部キー貼るときは参照先と参照元でカラム名が違っても大丈夫です。

2020-09-03 02:20 UTC, Yuzunoha commented
rooms.is_sendable_file は英文法的に
rooms.is_file_sendable にしましょう

2020-09-03 02:22 UTC, Yuzunoha commented
エクセルに uploaded_user_id というカラム名がありますがddlには無いですね。
全体定期にエクセルとddlで名前の不整合が無いか確認をお願いします！

2020-09-03 03:13 UTC, fu10ta commented
不要な接頭辞の削除
英文法的な命名の修正
エクセルとDDL文の整合性の確認

上記三点のレビュー修正をいたしました。

2020-09-03 04:20 UTC, fu10ta commented
エクセルとDDL文の整合性の確認
電話番号の命名変更

2020-09-03 06:34 UTC, Yuzunoha approved these changes
OKです！！承認しました！！！

2020-09-09 12:52 UTC, merged